"""create_notepad_model

Revision ID: 87ea056116f7
Revises: 7824e77e2729
Create Date: 2024-11-23 22:35:34.790978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87ea056116f7'
down_revision = '7824e77e2729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
